/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

int main(void)
{
    /* Loop forever */
	while(1)
    {
        /* Toggle LED LD1 */
        //HAL_GPIO_TogglePin(LD1_GPIO_Port, LD1_Pin);
        
        /* Delay for 2000 ms */
        //HAL_Delay(2000);
    }
}

/**
 * @brief Error Handler
 * This function is executed in case of error occurrence.
 * @retval None
 */
void error_handler(void)
{
    /* User can add his own implementation to report the HAL error return state */
    __disable_irq();
    while (1)
    {
        /* Stay in this loop in case of error */
    }
}